### ISSUE TITLE
Error with self.videoURL = url

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [PiXeL16/VideoBackgroundViewController#3]
<img width="683" alt="screen shot 2017-07-09 at 10 07 29 pm" src="https://user-images.githubusercontent.com/18103561/27996810-0bf9b66c-64f3-11e7-84ce-c5206c653927.png">

I uploaded a mp4 video and did the setup for the pod but I don't know why this error is showing

**Comment by PiXeL16** [comment]
You need to inherit your `ViewControlller` from `VideoBackgroundViewController` and not `UIViewController`
